// Sources flattened with hardhat v2.28.6 https://hardhat.org

// SPDX-License-Identifier: MIT

// File contracts/GroupRegistry.sol

// Original license: SPDX_License_Identifier: MIT
pragma solidity ^0.8.24;

/// @title GroupRegistry
/// @notice Manages group creation, membership, and per-market resolver assignment.
contract GroupRegistry {
    // ─── Structs ────────────────────────────────────────────────────────────────

    struct Group {
        bytes32 id;
        address admin;
        string name;
        bool exists;
    }

    // ─── State ──────────────────────────────────────────────────────────────────

    mapping(bytes32 => Group) public groups;
    mapping(bytes32 => mapping(address => bool)) public members;

    /// @dev marketId → resolver address (set by group admin at market creation time)
    mapping(bytes32 => address) public resolvers;

    /// @dev groupId → member list for off-chain enumeration
    mapping(bytes32 => address[]) private _memberList;

    // ─── Events ─────────────────────────────────────────────────────────────────

    event GroupCreated(bytes32 indexed groupId, address indexed admin, string name);
    event MemberJoined(bytes32 indexed groupId, address indexed member);
    event ResolverAssigned(bytes32 indexed marketId, address indexed resolver, bytes32 indexed groupId);

    // ─── Errors ─────────────────────────────────────────────────────────────────

    error GroupNotFound(bytes32 groupId);
    error NotGroupAdmin(bytes32 groupId, address caller);
    error ZeroAddress();
    error EmptyName();

    // ─── Modifiers ──────────────────────────────────────────────────────────────

    modifier onlyGroupAdmin(bytes32 groupId) {
        if (!groups[groupId].exists) revert GroupNotFound(groupId);
        if (groups[groupId].admin != msg.sender) revert NotGroupAdmin(groupId, msg.sender);
        _;
    }

    // ─── Group Management ────────────────────────────────────────────────────

    /// @notice Create a new prediction group.
    /// @param name Human-readable group name.
    /// @return groupId keccak256-derived on-chain group identifier.
    function createGroup(string calldata name) external returns (bytes32 groupId) {
        if (bytes(name).length == 0) revert EmptyName();

        groupId = keccak256(abi.encodePacked(name, msg.sender, block.timestamp));

        groups[groupId] = Group({
            id: groupId,
            admin: msg.sender,
            name: name,
            exists: true
        });

        // Creator is automatically a member
        members[groupId][msg.sender] = true;
        _memberList[groupId].push(msg.sender);

        emit GroupCreated(groupId, msg.sender, name);
        emit MemberJoined(groupId, msg.sender);
    }

    /// @notice Join a group via invite link. Idempotent — safe to call multiple times.
    /// @param groupId The group to join.
    function joinGroup(bytes32 groupId) external {
        if (!groups[groupId].exists) revert GroupNotFound(groupId);

        // Idempotent: do not revert if already a member, just emit and return
        if (!members[groupId][msg.sender]) {
            members[groupId][msg.sender] = true;
            _memberList[groupId].push(msg.sender);
            emit MemberJoined(groupId, msg.sender);
        }
    }

    /// @notice Assign a Trusted Resolver for a specific market.
    ///         Only callable by the group admin. Resolver is intentionally separate from admin.
    /// @param groupId  The group that owns this market.
    /// @param marketId On-chain market identifier (generated by PredictionMarket).
    /// @param resolver Address of the trusted resolver.
    function assignResolver(
        bytes32 groupId,
        bytes32 marketId,
        address resolver
    ) external onlyGroupAdmin(groupId) {
        if (resolver == address(0)) revert ZeroAddress();
        resolvers[marketId] = resolver;
        emit ResolverAssigned(marketId, resolver, groupId);
    }

    // ─── Views ───────────────────────────────────────────────────────────────

    function isGroupMember(bytes32 groupId, address user) external view returns (bool) {
        return members[groupId][user];
    }

    function getGroup(bytes32 groupId)
        external
        view
        returns (bytes32 id, address admin, string memory name, bool exists)
    {
        Group storage g = groups[groupId];
        return (g.id, g.admin, g.name, g.exists);
    }

    /// @notice Returns all member addresses for a group (for off-chain indexing).
    function getMembers(bytes32 groupId) external view returns (address[] memory) {
        return _memberList[groupId];
    }

    function getResolver(bytes32 marketId) external view returns (address) {
        return resolvers[marketId];
    }
}
